# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simple1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simple1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsimple1.proto\x12\x04todo\".\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"/\n\x11\x43reateTodoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\".\n\x12\x43reateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"\x1c\n\x0eGetTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x0fGetTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\";\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\".\n\x12UpdateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10ListTodosRequest\".\n\x11ListTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo2\xc6\x02\n\x0bTodoService\x12?\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\x18.todo.CreateTodoResponse\x12\x36\n\x07GetTodo\x12\x14.todo.GetTodoRequest\x1a\x15.todo.GetTodoResponse\x12?\n\nUpdateTodo\x12\x17.todo.UpdateTodoRequest\x1a\x18.todo.UpdateTodoResponse\x12?\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponse\x12<\n\tListTodos\x12\x16.todo.ListTodosRequest\x1a\x17.todo.ListTodosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=23
  _globals['_TODO']._serialized_end=69
  _globals['_CREATETODOREQUEST']._serialized_start=71
  _globals['_CREATETODOREQUEST']._serialized_end=118
  _globals['_CREATETODORESPONSE']._serialized_start=120
  _globals['_CREATETODORESPONSE']._serialized_end=166
  _globals['_GETTODOREQUEST']._serialized_start=168
  _globals['_GETTODOREQUEST']._serialized_end=196
  _globals['_GETTODORESPONSE']._serialized_start=198
  _globals['_GETTODORESPONSE']._serialized_end=241
  _globals['_UPDATETODOREQUEST']._serialized_start=243
  _globals['_UPDATETODOREQUEST']._serialized_end=302
  _globals['_UPDATETODORESPONSE']._serialized_start=304
  _globals['_UPDATETODORESPONSE']._serialized_end=350
  _globals['_DELETETODOREQUEST']._serialized_start=352
  _globals['_DELETETODOREQUEST']._serialized_end=383
  _globals['_DELETETODORESPONSE']._serialized_start=385
  _globals['_DELETETODORESPONSE']._serialized_end=422
  _globals['_LISTTODOSREQUEST']._serialized_start=424
  _globals['_LISTTODOSREQUEST']._serialized_end=442
  _globals['_LISTTODOSRESPONSE']._serialized_start=444
  _globals['_LISTTODOSRESPONSE']._serialized_end=490
  _globals['_TODOSERVICE']._serialized_start=493
  _globals['_TODOSERVICE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
